import React from 'react';
import { Settings, ShieldAlert, Droplets, HardHat, Package, Wrench } from 'lucide-react';

const categories = [
    {
        category: 'Metal Scrap & Recovery',
        examples: 'High volumes of ferrous and non-ferrous scrap, carbon steel plate cut-offs, #1 busheling, stainless steel chips, aluminum borings, copper wire, and decommissioned machinery.',
        handling: 'State-of-the-art size reduction, magnetic separation, eddy current sorting, and precise alloy segregation.',
        icon: Settings,
    },
    {
        category: 'Process Residues',
        examples: 'Industrial sludge, electric arc furnace (EAF) dust, baghouse fines, slag, scale, and process residues requiring specialized stabilization.',
        handling: 'Routed for chemical stabilization, safe reclamation, or compliant, licensed disposal.',
        icon: HardHat,
    },
    {
        category: 'Hazardous Chemicals',
        examples: 'Used oils, greases, heavy lubricants, hydraulic fluids, and chemical treatments/coatings by-products generated by heavy manufacturing.',
        handling: 'Safe containment, hazardous waste profiling, and transportation to permitted treatment and destruction facilities.',
        icon: Droplets,
    },
    {
        category: 'Refractory Materials',
        examples: 'Spent refractory bricks, insulation materials, and thermal linings systematically removed from industrial furnaces and ladles.',
        handling: 'Specialized handling, safe heavy-duty containment, and targeted industrial recycling or compliant landfilling.',
        icon: ShieldAlert,
    },
    {
        category: 'Packaging Materials',
        examples: 'Operational waste from the factory floor, including large wooden pallets, industrial plastics, and heavy-duty packaging materials.',
        handling: 'Thorough segregation and recycling programs supporting broader sustainability initiatives and operational efficiency.',
        icon: Package,
    },
    {
        category: 'Maintenance Scrap',
        examples: 'Heavy rollers, worn machinery parts, decommissioned operational equipment, and scrap generated from extensive heavy machinery maintenance.',
        handling: 'Secure, heavy-lift transportation and advanced processing to recover highly valuable reusable components.',
        icon: Wrench,
    },
];

const SteelPrimaryMetalsCategories = () => {
    return (
        <section className="steel-categories bg-white dark:bg-black !py-0">
            <div className="steel-categories__container max-w-screen-2xl mx-0 md:mx-auto px-0 flex flex-col gap-4 md:gap-[24px]">
                <div className="steel-categories__header text-center flex flex-col items-center gap-2 md:gap-4 scroll-reveal">
                    <h6 className="steel-categories__label text-[#47622A] dark:text-[#799851] uppercase">Waste Streams</h6>
                    <h2 className="steel-categories__heading !text-transparent !bg-clip-text bg-gradient-to-r from-[#47622A] to-[#799851]">
                        Complex Waste Streams We Manage
                    </h2>
                    <p className="steel-categories__subtitle dark:text-gray-400 text-gray-600 max-w-3xl">
                        Customized, compliant waste handling programs designed for heavy industry, focused on both disposal and resource recovery.
                    </p>
                </div>

                <div className="steel-categories__grid-wrapper scroll-reveal max-w-[1152px] mx-0 md:mx-auto w-full">
                    <div className="steel-categories__grid-outer overflow-hidden rounded-3xl border border-[#47622A]/10 dark:border-[#799851]/20 bg-gradient-to-br from-[#47622A]/5 to-[#799851]/5 dark:from-[#799851]/10 dark:to-[#47622A]/10 backdrop-blur-md bg-white/90 dark:bg-[#111]/90 shadow-sm">
                        
                        {/* Grid Header */}
                        <div className="steel-categories__grid-header grid grid-cols-[1.2fr_2fr_2fr] md:grid-cols-[1fr_2fr_2fr] bg-[#47622A] dark:bg-[#1a1a1a] border-b dark:border-white/10 border-transparent text-white dark:text-gray-200">
                            <h6 className="steel-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center border-r md:border-r-0 border-white/20">Category</h6>
                            <h6 className="steel-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center border-r md:border-r-0 border-white/20">Examples</h6>
                            <h6 className="steel-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center">Handling</h6>
                        </div>

                        {/* Grid Body */}
                        <div className="steel-categories__grid-body flex flex-col divide-y dark:divide-white/5 divide-gray-100">
                            {categories.map((cat, index) => {
                                const Icon = cat.icon;
                                return (
                                <div key={index} className="steel-categories__grid-row grid grid-cols-[1.2fr_2fr_2fr] md:grid-cols-[1fr_2fr_2fr] hover:bg-gray-50 dark:hover:bg-white/5 transition-colors">
                                    <div className="steel-categories__cell steel-categories__td-category p-2 md:p-[12px] font-bold dark:text-gray-200 text-[#47622A] text-center md:text-left flex flex-col md:flex-row items-center justify-center md:justify-start gap-1 md:gap-[8px] border-r md:border-r-0 border-gray-100 dark:border-white/5">
                                        <div className="flex md:hidden items-center justify-center w-[28px] h-[28px] rounded-full border dark:border-white/5 border-gray-100 shrink-0">
                                            <Icon className="w-[14px] h-[14px]" />
                                        </div>
                                        <p className="text-[16px] md:text-base leading-tight">{cat.category}</p>
                                    </div>
                                    <div className="steel-categories__cell steel-categories__td-examples p-2 md:p-[12px] text-[10px] md:text-base leading-tight md:leading-normal dark:text-gray-400 text-gray-600 text-center flex items-center justify-center border-r md:border-r-0 border-gray-100 dark:border-white/5">
                                        <p>{cat.examples}</p>
                                    </div>
                                    <div className="steel-categories__cell steel-categories__td-handling p-2 md:p-[12px] text-[10px] md:text-base leading-tight md:leading-normal dark:text-gray-400 text-gray-600 text-center flex items-center justify-center">
                                        <p>{cat.handling}</p>
                                    </div>
                                </div>
                            )})}
                        </div>

                    </div>
                </div>
            </div>
        </section>
    );
};

export default SteelPrimaryMetalsCategories;
