import React from 'react';
import { Package, AlignLeft, Lightbulb, Box, FileText, Lock, Copy } from 'lucide-react';

const categories = [
    {
        category: '#11 OCC (Cardboard)',
        examples: 'Old Corrugated Containers. Clean shipping boxes, product cartons, and packaging inserts.',
        handling: 'Must be dry and flattened/baled. Generated by retail stores and warehouses.',
        icon: Package,
    },
    {
        category: '#12 OCC',
        examples: 'Slightly lower grade OCC, may contain some non-kraft liners or labels.',
        handling: 'Gathered from smaller shops and mixed commercial waste streams.',
        icon: Box,
    },
    {
        category: 'Mixed Paper (MP)',
        examples: 'Unsorted office paper, white ledger, colored paper, magazines, and mail.',
        handling: 'Requires clean segregation from plastics and food waste.',
        icon: Copy,
    },
    {
        category: 'Soft Mixed Paper (SMP)',
        examples: 'Lower grade mixed paper, may include some low-quality cardboard.',
        handling: 'Processed through high-volume mixed commercial collection channels.',
        icon: AlignLeft,
    },
    {
        category: 'Shredded Confidential',
        examples: 'Security waste including cross-cut shredded corporate office paper.',
        handling: 'Requires secure transport, certified destruction, and closed chain-of-custody.',
        icon: Lock,
    },
    {
        category: 'Newsprint (ONP)',
        examples: 'Old newspapers and advertising inserts.',
        handling: 'Sourced from residential collections, institutions, and newspaper vendors.',
        icon: FileText,
    },
    {
        category: 'Industrial Paper',
        examples: 'Kraft paper, paper rolls and trims, paperboard, and chipboard.',
        handling: 'Volume management through on-site industrial compacting or baling operations.',
        icon: Factory,
    },
];

/* Note: Adding a fallback icon factory since Factory was not imported directly */
import { Factory } from 'lucide-react';

const PaperCardboardCategories = () => {
    return (
        <section className="paper-cardboard-categories bg-white dark:bg-black !py-0">
            <div className="paper-cardboard-categories__container max-w-screen-2xl mx-0 md:mx-auto px-0 flex flex-col gap-4 md:gap-[24px]">
                <div className="paper-cardboard-categories__header text-center flex flex-col items-center gap-2 md:gap-4 scroll-reveal">
                    <h6 className="paper-cardboard-categories__label text-[#47622A] dark:text-[#799851] uppercase">Capabilities</h6>
                    <h2 className="paper-cardboard-categories__heading !text-transparent !bg-clip-text bg-gradient-to-r from-[#47622A] to-[#799851]">
                        Key Grades We Handle
                    </h2>
                    <p className="paper-cardboard-categories__subtitle dark:text-gray-400 text-gray-600 max-w-3xl">
                        We manage and recycle the full spectrum of clean, dry paper-based materials, maintaining specific grade purities for top market value.
                    </p>
                </div>

                <div className="paper-cardboard-categories__grid-wrapper scroll-reveal max-w-[1152px] mx-0 md:mx-auto w-full">
                    <div className="paper-cardboard-categories__grid-outer overflow-hidden rounded-3xl border border-[#47622A]/10 dark:border-[#799851]/20 bg-gradient-to-br from-[#47622A]/5 to-[#799851]/5 dark:from-[#799851]/10 dark:to-[#47622A]/10 backdrop-blur-md bg-white/90 dark:bg-[#111]/90 shadow-sm">
                        
                        {/* Grid Header */}
                        <div className="paper-cardboard-categories__grid-header grid grid-cols-[1.2fr_2fr_2fr] md:grid-cols-[1fr_2fr_2fr] bg-[#47622A] dark:bg-[#1a1a1a] border-b dark:border-white/10 border-transparent text-white dark:text-gray-200">
                            <h6 className="paper-cardboard-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center border-r md:border-r-0 border-white/20">Grade / Category</h6>
                            <h6 className="paper-cardboard-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center border-r md:border-r-0 border-white/20">Description & Examples</h6>
                            <h6 className="paper-cardboard-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center">Handling / Source</h6>
                        </div>

                        {/* Grid Body */}
                        <div className="paper-cardboard-categories__grid-body flex flex-col divide-y dark:divide-white/5 divide-gray-100">
                            {categories.map((cat, index) => {
                                const Icon = cat.icon;
                                return (
                                <div key={index} className="paper-cardboard-categories__grid-row grid grid-cols-[1.2fr_2fr_2fr] md:grid-cols-[1fr_2fr_2fr] hover:bg-gray-50 dark:hover:bg-white/5 transition-colors">
                                    <div className="paper-cardboard-categories__cell paper-cardboard-categories__td-category p-2 md:p-[12px] font-bold dark:text-gray-200 text-[#47622A] text-center md:text-left flex flex-col md:flex-row items-center justify-center md:justify-start gap-1 md:gap-[8px] border-r md:border-r-0 border-gray-100 dark:border-white/5">
                                        <div className="flex md:hidden items-center justify-center w-[28px] h-[28px] rounded-full border dark:border-white/5 border-gray-100 shrink-0">
                                            <Icon className="w-[14px] h-[14px]" />
                                        </div>
                                        <p className="text-[16px] md:text-base leading-tight">{cat.category}</p>
                                    </div>
                                    <div className="paper-cardboard-categories__cell paper-cardboard-categories__td-examples p-2 md:p-[12px] text-[10px] md:text-base leading-tight md:leading-normal dark:text-gray-400 text-gray-600 text-center flex items-center justify-center border-r md:border-r-0 border-gray-100 dark:border-white/5">
                                        <p>{cat.examples}</p>
                                    </div>
                                    <div className="paper-cardboard-categories__cell paper-cardboard-categories__td-handling p-2 md:p-[12px] text-[10px] md:text-base leading-tight md:leading-normal dark:text-gray-400 text-gray-600 text-center flex items-center justify-center">
                                        <p>{cat.handling}</p>
                                    </div>
                                </div>
                            )})}
                        </div>

                    </div>
                </div>
            </div>
        </section>
    );
};

export default PaperCardboardCategories;
