import React from 'react';
import { Trash2, Recycle, Biohazard, Hammer, FileText, Monitor } from 'lucide-react';

const categories = [
    {
        category: 'General Operational Waste',
        examples: 'Daily operational and office waste, requiring clean, hygienic handling.',
        handling: 'Flexible, scheduled pickups with compliant bins to maintain a pristine small business environment.',
        icon: Trash2,
    },
    {
        category: 'Recyclable Materials',
        examples: 'High-volume packaging materials such as cardboard, plastics, glass, metals, and pallets.',
        handling: 'Collection and processing to significantly reduce landfill impact and support sustainable practices.',
        icon: Recycle,
    },
    {
        category: 'Hazardous Materials',
        examples: 'Cleaning chemicals, solvents, used oil, coolant, aerosol cans, and batteries.',
        handling: 'Safe collection, strict segregation, and regulatory treatment to prevent any environmental penalties.',
        icon: Biohazard,
    },
    {
        category: 'Commodity Scrap & Metals',
        examples: 'Ferrous and non-ferrous metals, obsolete machinery, debris, and production by-products.',
        handling: 'Transparent purchasing and recycling to convert your overlooked assets into a predictable minor income stream.',
        icon: Hammer,
    },
    {
        category: 'Sensitive Data',
        examples: 'Confidential documents, customer records, and critical privacy information.',
        handling: 'Certified secure destruction to ensure absolute compliance with privacy and data protection regulations.',
        icon: FileText,
    },
    {
        category: 'E-Waste & Electronics',
        examples: 'IT equipment, computers, electronics, small servers, and fluorescent/LED lamps.',
        handling: 'Safe, certified recycling paired with secure data wiping to protect sensitive business information.',
        icon: Monitor,
    },
];

const SmallBusinessesCategories = () => {
    return (
        <section className="small-businesses-categories bg-white dark:bg-black !py-0">
            <div className="small-businesses-categories__container max-w-screen-2xl mx-0 md:mx-auto px-0 flex flex-col gap-4 md:gap-[24px]">
                <div className="small-businesses-categories__header text-center flex flex-col items-center gap-2 md:gap-4 scroll-reveal">
                    <h6 className="small-businesses-categories__label text-[#47622A] dark:text-[#799851] uppercase">Capabilities</h6>
                    <h2 className="small-businesses-categories__heading !text-transparent !bg-clip-text bg-gradient-to-r from-[#47622A] to-[#799851]">
                        Diverse Waste Streams We Manage
                    </h2>
                    <p className="small-businesses-categories__subtitle dark:text-gray-400 text-gray-600 max-w-3xl">
                        We provide comprehensive solutions for the varied waste streams generated by businesses like retail stores, offices, cafes, and small manufacturing units.
                    </p>
                </div>

                <div className="small-businesses-categories__grid-wrapper scroll-reveal max-w-[1152px] mx-0 md:mx-auto w-full">
                    <div className="small-businesses-categories__grid-outer overflow-hidden rounded-3xl border border-[#47622A]/10 dark:border-[#799851]/20 bg-gradient-to-br from-[#47622A]/5 to-[#799851]/5 dark:from-[#799851]/10 dark:to-[#47622A]/10 backdrop-blur-md bg-white/90 dark:bg-[#111]/90 shadow-sm">
                        
                        {/* Grid Header */}
                        <div className="small-businesses-categories__grid-header grid grid-cols-[1.2fr_2fr_2fr] md:grid-cols-[1fr_2fr_2fr] bg-[#47622A] dark:bg-[#1a1a1a] border-b dark:border-white/10 border-transparent text-white dark:text-gray-200">
                            <h6 className="small-businesses-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center border-r md:border-r-0 border-white/20">Category</h6>
                            <h6 className="small-businesses-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center border-r md:border-r-0 border-white/20">Examples</h6>
                            <h6 className="small-businesses-categories__th p-2 md:p-[12px] text-[16px] md:text-base font-bold uppercase tracking-wider text-center">Handling</h6>
                        </div>

                        {/* Grid Body */}
                        <div className="small-businesses-categories__grid-body flex flex-col divide-y dark:divide-white/5 divide-gray-100">
                            {categories.map((cat, index) => {
                                const Icon = cat.icon;
                                return (
                                <div key={index} className="small-businesses-categories__grid-row grid grid-cols-[1.2fr_2fr_2fr] md:grid-cols-[1fr_2fr_2fr] hover:bg-gray-50 dark:hover:bg-white/5 transition-colors">
                                    <div className="small-businesses-categories__cell small-businesses-categories__td-category p-2 md:p-[12px] font-bold dark:text-gray-200 text-[#47622A] text-center md:text-left flex flex-col md:flex-row items-center justify-center md:justify-start gap-1 md:gap-[8px] border-r md:border-r-0 border-gray-100 dark:border-white/5">
                                        <div className="flex md:hidden items-center justify-center w-[28px] h-[28px] rounded-full border dark:border-white/5 border-gray-100 shrink-0">
                                            <Icon className="w-[14px] h-[14px]" />
                                        </div>
                                        <p className="text-[16px] md:text-base leading-tight">{cat.category}</p>
                                    </div>
                                    <div className="small-businesses-categories__cell small-businesses-categories__td-examples p-2 md:p-[12px] text-[10px] md:text-base leading-tight md:leading-normal dark:text-gray-400 text-gray-600 text-center flex items-center justify-center border-r md:border-r-0 border-gray-100 dark:border-white/5">
                                        <p>{cat.examples}</p>
                                    </div>
                                    <div className="small-businesses-categories__cell small-businesses-categories__td-handling p-2 md:p-[12px] text-[10px] md:text-base leading-tight md:leading-normal dark:text-gray-400 text-gray-600 text-center flex items-center justify-center">
                                        <p>{cat.handling}</p>
                                    </div>
                                </div>
                            )})}
                        </div>

                    </div>
                </div>
            </div>
        </section>
    );
};

export default SmallBusinessesCategories;
